spring:
  mvc: 
    view: 
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: ${PORT:8180}
---
spring:
  profiles: dev
server:
  port: ${PORT:8180}
---
spring:
  profiles: real
server:
  port: ${PORT:8180}