spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
server:
  port: ${PORT:8401}
log4jdbc:
  drivers: org.mariadb.jdbc.Driver
  spylogdelegator: 
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump: 
    sql:
      maxlinelength: 0

mybatis: 
  configuration: 
    map-underscore-to-camel-case: true
  config-location: mybatis/mybatis-config.xml

# -- Eureka client
eureka:
  client: 
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 2
    #registry-fetch-interval-seconds: 3
    disable-delta: true
    serviceUrl:
      #defaultZone: ${EUREKA_URL:http://192.168.135.128:8761/eureka/}
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
      #defaultZone: http://localhost:8761/eureka/
      
#beans       application의 전체 Spring beans를 출력
#caches      사용가능한 cache를 노출
#conditions  configuration 또는 auto-configuration 되는 class들의 성공 여부와 이유를 설명
#env         Spring Boot의 현재 환경설정 정보(application.yml의 정보 등)를 출력
#health      application의 현재 상태를 보여줍니다.
#httptrace   http를 trace한 정보를 노출(기본적으로 최신 100건의 reqest-response를 보여줍니다.)
#mappings    Request와 mapping되어있는 handler 정보를 가져옵니다.
#sessions    Spring Session이 가지고 있는 정보를 가져옵니다.
#threaddump  threaddump를 가져옴
#logfile     log를 가져옵니다.
#metrics     metrics 정보를 노출합니다.
management:
  endpoint:
    shutdown:
      enabled: true
      sensitive: false #보안해제
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
    profiles: dev
server:
    port: ${PORT:8401}
---
spring:
    profiles: real
server:
    port: ${PORT:8401}
