spring:
  profiles:
    active: real
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000

log4jdbc:
  drivers: org.mariadb.jdbc.Driver
  spylogdelegator: 
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump: 
    sql:
      maxlinelength: 0

mybatis: 
  configuration: 
    map-underscore-to-camel-case: true
  config-location: mybatis/mybatis-config.xml

# -- Eureka client
eureka:
  client: 
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    registry-fetch-interval-seconds: 3
    disable-delta: true
    serviceUrl:
      #defaultZone: ${EUREKA_URL:http://192.168.135.128:8761/eureka/}
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
      #defaultZone: http://localhost:8761/eureka/